name: Create Test Cycle

on:
  workflow_dispatch:
    inputs:
      testCycleKey:
        description: "QMetry Test Cycle Key"
        required: false

jobs:
  create-cycle:
    runs-on: ubuntu-latest

    steps:
      - name: Print Test Cycle Key
        run: |
          echo "Test Cycle Key: ${{ github.event.inputs.testCycleKey }}"

      - name: Create QMetry Test Cycle
        run: |
          curl --location 'https://qtmcloud.qmetry.com/rest/api/latest/testcycles' \
          --header 'Accept: application/json' \
          --header 'apiKey: ${{ secrets.QMETRY_API_KEY }}' \
          --header 'Content-Type: application/json' \
          --data '{
            "projectId": 10001,
            "summary": "Triggered from cycle: ${{ github.event.inputs.testCycleKey }}",
            "description": "Cycle Key: ${{ github.event.inputs.testCycleKey }} | GitHub Run: ${{ github.run_id }}",
            "folderId": -1
          }'
